title_html: "<b>alessandro</b>lad"
baseurl: "/academic" # the subpath of your site, e.g. /blog
description: "ok, I'll add a description here."
# pitch: strategy, digital innovation and china
title: alessandro
